### ISSUE TITLE
how to??

### ISSUE THREAD

**Issue by cisko99za** [Tick-Org/Musick#3]
hi, sorry for my intrusion.... but i would be interested in it....
how to work on windows???? what should i do to run this on my windows pc???

**Comment by pythongiant** [comment]
Hi @cisko99za run these commands as mentioned in the README

```
git clone https://github.com/Tick-Org/Musick
# install dependencies
npm install
# build 
npm run build
# run the app
python3 run.py
```

**Comment by cisko99za** [comment]
mmm... tanxs... i have read README... but if i wrote here it means i don't know what to do.....
npm install .... where find it? link...
npm run build  ??? what does it mean.... explain me step by step, please...!

**Comment by nileshpatra** [comment]
Hi @cisko99za I suggest that you read the following before you communicate any further:

-  [Communication Guidelines](https://dgplug.org/irclogs/mbuf_1stclass.log)
- [Read the docs](https://summertraining.readthedocs.io/en/latest/commguidelines.html)

Also, learn about npm - what it is, how to install it, and how to build via it, before you start with this project. You can also have a look [here](https://docs.npmjs.com/about-npm/), for a brief idea.

**Comment by cisko99za** [comment]
it's more complicated install npm...
i need portable version...

**Comment by pythongiant** [comment]
@cisko99za i suggest you read about the command line and how to use it

**Comment by cisko99za** [comment]
i know cmd but npm (with install.bat inside) install a lot of things (new framework 4.8, Microsoft Visual C++, and other things....) 
i don't want install all! i want simple method to use your run.py (python 3 i installed it)

**Comment by cisko99za** [comment]
or another simple method to download my spotify playlist....
